### ISSUE TITLE
Do we know absolute position in real space?

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/xBOUT#116]
So I'm making some plots where I have different-sized parallel domains all of which I want to centre on the same point in real space (the mid-plane). Opening the data with xstorm returns the parallel coordinate in real space as starting at 0 on the lower target every time. It would be nice if xBOUT/xstorm automatically centred the results on the mid-plane before returning them to me, but I'm not actually sure whether there is enough information in the dump files and input file to know this? BOUT only returns `dy` right, so we don't know the integration constant? Also how would xBOUT know if I was doing a target-to-target or a mid-plane-to-target simulation?

![S_profiles_vs_leg](https://user-images.githubusercontent.com/35968931/79054246-589fbe00-7c3b-11ea-97b6-728070743be1.png)

**Comment by johnomotani** [comment]
I don't think there's a totally generic solution, because someone might have a slab simulation that isn't symmetric, e.g. a slab approximation to a single-null SOL, where the sources are closer to one target than the other. @TomNicholas the short answers to your questions are: BOUT++ doesn't generically know where a symmetry plane is, but STORM does; BOUT++ indeed only uses/stores `dx`, `dy` and `dz`, it doesn't define global coordinates which have the integration constant fixed.

One question is what a sensible default would be, and having the parallel distance be zero in the centre for the slab geometry function seems like a good one to me.

Another question is should we provide some generic support for offsetting or transforming coordinates. We could provide some argument to `apply_geometry` like `offset_coords` so you could do something like `apply_geometry("slab", offset_coords={"parallel": -Ly/2.})`, or even a more generic transformation like `apply_geometry("slab", transform_coords={"parallel": lambda y: y - y.max()/2.})`. I don't think we should though, I think the place for this is in a physics-model specific accessor like xSTORM, because it's easy enough to do something like `ds["parallel"] = ds["parallel"] - Ly/2.` in open_stormdataset, or even in a user-registered `apply_geometry`.

Summary - my vote would go to:
1. making the parallel coordinate default to having zero at the centre for slab simulations (if we register a slab geometry in xBOUT, which it would seem sensible to me to do).
2. leave any customisation of the coordinates to model-specific accessors (e.g. xstorm).

**Comment by TomNicholas** [comment]
> short answers to your questions are: BOUT++ doesn't generically know where a symmetry plane is, but STORM does;

Thanks @johnomotani , that's what I suspected.

> I don't think we should though, I think the place for this is in a physics-model specific accessor like xSTORM

I agree that that's a complicated that should be handled by physics-module-specific code.

> making the parallel coordinate default to having zero at the centre for slab simulations (if we register a slab geometry in xBOUT, which it would seem sensible to me to do).

But if we add a slab geometry what will it return if not SI-units (which it can't in bare xBOUT)? Is there much point in adding `x_int` when it's almost the same as the indices of the `x` dimension?

**Comment by johnomotani** [comment]
Yeah, I don't know if it's worth having a slab geometry. If we have x, y, z coordinates that are integrated `dx`, `dy`, `dz`, then we'd get axes in units of `rho_s` right? That could be mildly useful, and there'd be a skeleton there if it turns out in future that there's some functionality that we could add for a slab. But I agree I'm not convinced that a slab geometry is actually worth adding until we have more that we actually want it to do...

**Comment by TomNicholas** [comment]
> Yeah, I don't know if it's worth having a slab geometry. If we have x, y, z coordinates that are integrated dx, dy, dz, then we'd get axes in units of rho_s right? 

You're already assuming that your base normalisation is `rho_s`, what if it's a chocolate system or something? I agree a slab geometry without knowing the model-specific normalisations probably isn't useful enough to put in xBOUT, it should just go in the model-specific wrappers.

I'm going to close this in favour of adding it specifically to the xstorm slab geometry. (in xstorm MR !23)
