### ISSUE TITLE
missing dependency on py

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/xBOUT#145]
py is a dependency of xbout - but it is not pulled in, as far as I can tell:
```
In [1]: import xbout                                                            
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fe6f7ed77132> in <module>
----> 1 import xbout

/usr/lib/python3.9/site-packages/xbout/__init__.py in <module>
----> 1 from .load import open_boutdataset, collect
      2 
      3 from . import geometries
      4 from .geometries import register_geometry, REGISTERED_GEOMETRIES
      5 

/usr/lib/python3.9/site-packages/xbout/load.py in <module>
      2 from warnings import warn
      3 from pathlib import Path
----> 4 from py._path.local import LocalPath
      5 from functools import partial
      6 from itertools import chain

ModuleNotFoundError: No module named 'py'
```

after installing `py` with pip, xbout works.

However, `py` is apparently in [maintainance mode](https://pypi.org/project/py/) and should not be used in new code

**Comment by johnomotani** [comment]
`py` is still being used by `pytest` for its `tmpdir_factory` functionality https://github.com/pytest-dev/pytest/blob/78ed3e48db7766ccef1b2c456879b6ee01df0986/src/_pytest/tmpdir.py#L8.

It's being used to check whether a `datapath` argument is actually a path (i.e. `str`, `Path` or `py.path.LocalPath`) so that we can add special handling in the opposite case (where `datapath` is a `Dataset` or list of `Dataset`s). I think we can avoid the (direct) dependency with a duck-check.
